extern fun_entry_t premod_console_funs[];
extern uint8_t premod_console_strings[];

extern fun_entry_t premod_erl_prim_loader_funs[];
extern uint8_t premod_erl_prim_loader_strings[];

extern fun_entry_t premod_erlang_funs[];
extern uint8_t premod_erlang_strings[];

extern fun_entry_t premod_error_handler_funs[];
extern uint8_t premod_error_handler_strings[];

extern fun_entry_t premod_init_funs[];
extern uint8_t premod_init_strings[];

extern fun_entry_t premod_prim_inet_funs[];
extern uint8_t premod_prim_inet_strings[];

#define EH_UNDEF_EXP	(preloaded_exports+406)

